- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemErrors.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
- Tests/DistributedSystemTests/GenericDistributedActor.swift
Add possibility to set a timeout for service discovery.
> fix(patch): [sc-3705] Connect to service with timeout.

- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/DiscoveryManager.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemServer.swift
Swift Logger has an internal metadata storage which simpler to use.
Unit tests.
> chore(patch): [sc-3758] Use logger internal metadata instead of external.

- Sources/DistributedSystem/EndpointIdentifier.swift
- Sources/DistributedSystem/InvocationEnvelope.swift
- Sources/ForTesting/TestMessages/TestProtocols.swift
- Sources/ForTesting/TestMessages/TestServiceEndpoint.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
- Tests/DistributedSystemTests/TransferableConformanceTests.swift
Array serialisation test is in the TransferableConformanceTests, so test for dictionary should be in the same place.
Unit tests.
> fix(patch): [sc-1690] Move dictionary serialisation test from DistributedSystemTests to TransferableConformanceTests

- Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift
- Benchmarks/DistributedSystem/ServerAndClient.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemErrors.swift
- Sources/DistributedSystem/RemoteCallResultHandler.swift
- Sources/DistributedSystem/SyncCallManager.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
Suspend distributed calls for the endpoing if inbound queue on the receiver side is big.
> fix(patch): [sc-1690] Suspend distributed calls for the endpoing if inbound queue on the receiver side is big.

- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/EndpointIdentifier.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
Fix problem with message size for suspend/resume requests.
Unit tests.
> fix(patch): [sc-7847] Fix problem with message size for suspend/resume requests.

- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemServer.swift
Log a warning message when the channel's outbound queue size reach 1Mb, 2Mb, 4Mb etc.
> fix(patch): [sc-7972] Log a warning message when channel outbound queue grow

- Sources/DistributedSystem/DistributedSystem.swift
Pass log level as an optional argument to `DistributedSystem` initializer.
> chore(minor): add ability to specify log level for DistributedSystem [sc-1847]

- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemErrors.swift
connectToService() throws specific error instead of generic string.
Unit tests.
> fix(patch): [sc-8192] connectToService() throws specific error instead of generic string.

- Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemErrors.swift
- Sources/DistributedSystem/ModuleIdentifier.swift
- Sources/ForTesting/TestService/TestService.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
- Tests/DistributedSystemTests/GenericDistributedActor.swift
- Tests/DistributedSystemTests/TransferableConformanceTests.swift
Having it in the module will give a possibility to import only the ModuleIdentifier type instead of the whole DistributedSystem module.
Unit tests.
> fix(major): [sc-82] Move ModuleIdentifier from DistributedSystem type to the DistributedSystem module.

- Sources/DistributedSystem/DistributedSystem.swift
Set default log level to info.
Unit tests.
> fix(patch): [sc-8927] Set default log level to info.

- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/EndpointIdentifier.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
Release local client endpoint when server endpoint resign.
Unit tests.
> fix(patch): [sc-8927] Release local client endpoint when server endpoint resign.

- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
Notify connection state properly for remote client endpoints.
Unit tests.
> fix(patch): [sc-9383] Notify connection state properly for remote client endpoints.

- Sources/DistributedSystem/ChannelCompression.swift
- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/ChannelHandshake.swift
- Sources/DistributedSystem/DistributedSystem.swift
Fix logs: log both local and remote address for TCP session.
Unit tests.
> fix(patch): [sc-9314] Fix logs: log both local and remote address for TCP session.

- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/InvocationEnvelope.swift
Encode remote target names as integer to reduce e amount of transmitted data.
Unit tests.
> fix(patch): [sc-10502] Encode remote target names as integer.

- Package.swift
- Sources/lz4/lz4shims.h
- Sources/lz4/module.modulemap
Use lz4 provided by package-system-libs instead of own declared system library to avoid conflicts.
Unit tests.
> fix(patch): [sc-6337] Use lz4 provided by package-system-libs instead of own declared.

- Sources/DistributedSystem/ChannelCompression.swift
- Sources/DistributedSystem/ChannelCounters.swift
- Sources/DistributedSystem/DistributedSystem.swift
Seems like deinitialization does not work well for statistic update,
let's try to update compression stats on channel inactivation instead.
Unit tests.
> fix(patch): [sc-6337] Update compression stats in DS on channel inactivation.

- Sources/DistributedSystem/DiscoveryManager.swift
Avoid connection to process if service filter returned false.
Manual tests.
> fix(patch): [sc-11234] Avoid connection to process if service filter returned false.

- Benchmarks/DistributedSystem/ServerAndClient.swift
- Package.swift
Remove dependency on package-latency-tools.
Unit tests.
> fix(patch): [sc-6593] Remove dependency on package-latency-tools.

- Sources/DistributedSystem/DiscoveryManager.swift
- Sources/DistributedSystem/DistributedSystemServer.swift
Handle properly a case when first service registration failed.
In the case if first service registration failed and health status update requested,
then health status update was not actually scheduled and services soon would be
deregistered in the `Consul`.
> fix(patch): [sc-16656] Handle properly a case when first service registration failed.

- Sources/DistributedSystem/DiscoveryManager.swift
Log an error instead of fatalError() in case if DiscoveryManager.setAddress() called for unknown service.
> fix(patch): [sc-16715] Log an error instead of fatalError() in case if DiscoveryManager.setAddress() called for unknown service.

- Sources/DistributedSystem/DiscoveryManager.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
Reconnect properly in a case if service removed from the Consul and then appears again.
> fix(patch): [sc-16715] Reconnect properly in a case if service removed from the Consul and then appears again.

- Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift
- Benchmarks/DistributedSystem/ServerAndClient.swift
- README.md
- Sources/DistributedSystem/ChannelHandler.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/DistributedSystemErrors.swift
Log an error instead of fatalError() in a case if can't find channel for distributed actor.
> fix(patch): [sc-16715] Log an error instead of fatalError() in a case if can't find channel for distributed actor.

- Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift
- Benchmarks/DistributedSystem/ServerAndClient.swift
- Package.swift
- Sources/ForTesting/TestClient/TestClient.swift
> fix(patch): [sc-13510] Remove dependency on latency timer.

- Sources/DistributedSystem/ChannelCompression.swift
- Sources/DistributedSystem/ChannelCounters.swift
- Sources/DistributedSystem/ChannelHandshake.swift
- Sources/DistributedSystem/DistributedSystem.swift
- Sources/DistributedSystem/SyncCallManager.swift
- Tests/DistributedSystemTests/DistributedSystemTests.swift
> fix(major): [sc-13510] Use Data instead of UnsafeRawPointer to share dictionary to be Swift6 compliant.
