Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift, Benchmarks/DistributedSystem/ServerAndClient.swift, Sources/DistributedSystemConformance/Dictionary+Transferable.swift, Sources/DistributedSystemConformance/ULEB128.swift, Sources/ForTesting/TestClient/TestClient.swift, Sources/ForTesting/TestMessages/TestClientEndpoint.swift, Sources/ForTesting/TestMessages/TestProtocols.swift, Sources/ForTesting/TestMessages/TestServiceEndpoint.swift, Sources/ForTesting/TestService/TestService.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
Make Dictionary as Transferable.
Unit tests.
=> feat(patch): [sc-3762] Make Dictionary as Transferable.

Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
DistributedSystem.connectToService() now will be interrupted if the running task is cancelled.
=> fix(patch): [sc-3782] DistributedSystem.connectToService() interrupts if a running task is cancelled.

Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemErrors.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
=> fix(patch): [sc-3782] Cosmetic fix.

Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Sources/DistributedSystem/InvocationEnvelope.swift
Warning will appear if a queue size for particular endpoint will reach 1Mb
Unit tests.
=> fix(patch): [sc-1690] Log queue growing.

Sources/DistributedSystem/DistributedSystem.swift
=> fix(patch): [sc-1690] Cosmetic fix.

Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Sources/DistributedSystem/PingService.swift, Sources/DistributedSystem/RemoteCallDecoder.swift, Sources/DistributedSystem/RemoteCallResultHandler.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
… does not respond to ping messages.
Log a warning if opposite side of the connection does not respond to ping messages.
=> fix(major): [sc-2502] Log a warning if opposite side of the connection does not respond to ping messages.

Package.swift
Make DistributedSystemConformance dynamic.
Unit tests.
=> fix(patch): [sc-455] Make DistributedSystemConformance dynamic.

Package.swift
Make DistributedSystemConformance static
Make DistributedSystemConformance static
=> fix(patch): [sc-455] Make DistributedSystemConformance static.

Sources/DistributedSystem/DistributedSystem.swift
=> fix(patch): [sc-1690] adjusted defaults and log level

Package.swift
=> fix(major): [sc-455] Bump dependency version.

Package.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/RemoteCallDecoder.swift, Sources/ForTesting/TestMessages/TestMessages.swift, Tests/DistributedSystemTests/FrostflakeInitializer.swift
semver bump for [sc-5038] requested by @ser-0xff
=> feat(major): bump semver Bump dependency version [sc-5038]

Package.swift, Sources/ForTesting/TestMessages/TestMessages_generated.swift
=> chore(major): update fb dependency

Package.swift
semver bump for [sc-6788] requested by @dukhnyak
=> feat(minor): bump semver Consul logs [sc-6788]

Package.swift
=> fix(patch): [sc-7238] Add missing dependency

Package.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
semver bump for [sc-6843] requested by ser-0xff
=> feat(major): bump semver Bump dependency version. [sc-6843]

Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift
Add tagged addresses support.
Unit tests.
=> fix(patch): [sc-3261] Add tagged addresses support.

Sources/DistributedSystem/DistributedSystem.swift
Add address tag argument to initializer.
Unit tests.
=> fix(patch): [sc-82] Add address tag argument to initializer.

Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift
Add DS internal protocol compatibility check.
Unit tests.
=> fix(patch): [sc-3434] Add DS internal protocol compatibility check.

Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift, Benchmarks/DistributedSystem/ServerAndClient.swift, Package.swift, Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelOutboundCounter.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Sources/lz4/lz4shims.h, Sources/lz4/module.modulemap
=> fix(patch): [sc-6337] Add compression.

Sources/DistributedSystem/ChannelHandshake.swift
=> fix(patch): [sc-10587] Polish logs.

Sources/DistributedSystem/ChannelHandshake.swift
=> fix(patch): [sc-10691] Improve logging.

Package.swift
semver bump for [sc-12153] requested by ser-0xff
=> feat(major): bump semver bump dependencies. [sc-12153]

Package.swift, Sources/ForTesting/TestMessages/TestMessages.swift
Remove dependency on package-datetime.
Unit tests.
=> fix(patch): [sc-6593] Remove dependency on package-datetime.

.github/workflows/swift-macos-build.yml, Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift
Redesign server side pipeline management.
Unit tests.
=> fix(patch): [sc-11802] Redesign server side pipeline management.

.github/workflows/swift-macos-build.yml, Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DistributedSystem.swift
Redesign client side pipeline management.
Unit tests.
=> fix(patch): [sc-11802] Redesign client side pipeline management.

Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
Create proper service endpoint.
Unit tests.
=> fix(major): [sc-12609] Create proper service endpoint.

Package.swift
semver bump for [sc-14856] requested by ser-0xff
=> feat(major): bump semver Bump consul [sc-14856]

Benchmarks/DistributedSystem/ServerAndClient.swift, Package.swift, Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/RemoteCallEncoder.swift, Sources/DistributedSystem/SyncCallManager.swift, Sources/DistributedSystem/TransferableConformance/Array+Transferable.swift, Sources/DistributedSystem/TransferableConformance/Dictionary+Transferable.swift
Remove useless dependency.
Unit tests.
=> fix(patch): Remove useless dependency.

Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
Try to reconnect to service while it is in Consul.
API has not been changed, but changes are quite sensitive so let's make it as a major to be sure dependent projects will not be automatically switched to the new version.
Unit tests.
=> fix(major): [sc-10387] Try to reconnect to service while it is in Consul.

Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/EndpointIdentifier.swift
Extend logs and make EndpointIdentifier sendable.
=> fix(patch): [sc-16656] Extend logs and make EndpointIdentifier sendable.

Sources/DistributedSystem/DistributedSystemServer.swift
=> fix(patch): [sc-16656] Add some logs.

Sources/DistributedSystem/DiscoveryManager.swift
=> fix(patch): [sc-16747] Polish logs.

Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DistributedSystem.swift
Fix race in case when lose connection to service and connection state listener discover the service again.
=> fix(patch): [sc-16715] Fix race in case when lose connection to service and connection state listener discover the service again.

Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelCounters.swift, Sources/DistributedSystem/ChannelHandler.swift, Sources/DistributedSystem/ChannelHandshake.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Sources/DistributedSystem/InvocationEnvelope.swift, Sources/DistributedSystem/RemoteCallDecoder.swift, Sources/DistributedSystem/RemoteCallEncoder.swift, Sources/DistributedSystem/RemoteCallResultHandler.swift, Sources/DistributedSystem/SyncCallManager.swift
=> chore(patch): [sc-15918] make InvocationEnvelope to be public

Sources/DistributedSystem/DistributedSystemServer.swift
Register in the remote Consul agent with the local IP address.
=> fix(patch): [sc-16747] Register in the remote Consul agent with the local IP address.

Sources/DistributedSystem/TransferableConformance/Bool+Transferable.swift
=> fix(minor): [sc-17558] Add Transferable conformance for Bool type.

Sources/DistributedSystem/ChannelCompression.swift, Sources/DistributedSystem/ChannelHandler.swift, Sources/ForTesting/TestClient/TestClient.swift, Sources/ForTesting/TestService/TestService.swift
=> fix(patch): [sc-13510] Adopt for Swift 6.

Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/InvocationEnvelope.swift
=> fix(patch): [sc-13510] Manage function index in a Swift6 compliant way.

Benchmarks/DistributedSystem/ServerAndClient.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/Transferable.swift, Sources/ForTesting/TestMessages/TestMessages.swift, Sources/ForTesting/TestMessages/TestProtocols.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
=> fix(patch): [sc-13510] Make Transferable sendable.

Benchmarks/Benchmarks/DistributedSystem/DistributedSystemBenchmarks.swift, Benchmarks/Package.swift, Package.swift
=> fix(major): [sc-13510] Switch to Swift6.

Package.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/ForTesting/TestClient/TestClient.swift, Sources/ForTesting/TestService/TestService.swift
=> fix(patch): [sc-19217] Remove dependency on Lifecycle.

Package.swift, Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemServer.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
=> fix(major): [sc-19639] Add possibility to remove service.

Package.swift
=> fix(major): [sc-14892] Bump consul version.

Sources/DistributedSystem/DiscoveryManager.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/DistributedSystemErrors.swift, Sources/DistributedSystem/DistributedSystemServer.swift
=> fix(minor): [sc-19597] Add possibility to change metadata of the service in consul.

Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/InvocationEnvelope.swift
=> fix(major): [sc-22786] Make Box<> internal and remove useless target func encoding.

Sources/DistributedSystem/ChannelCounters.swift, Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/SyncCallManager.swift
=> fix(minor): [sc-21938] Add possibility to fetch traffic stats.

Sources/DistributedSystem/DistributedSystem.swift, Sources/DistributedSystem/RemoteCallResultHandler.swift, Sources/DistributedSystem/SyncCallManager.swift, Sources/ForTesting/TestMessages/TestServiceEndpoint.swift, Tests/DistributedSystemTests/DistributedSystemTests.swift
=> fix(major): [sc-16051] Propagate distributed actor thrown error properly.
